// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/Authentication/login": {
            "post": {
                "description": "Login for user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Insert Header Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/binning": {
            "post": {
                "description": "Get Binning List By Header",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags1Test"
                ],
                "summary": "Show An Binning List",
                "parameters": [
                    {
                        "description": "Insert Header Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/payloads.BinningHeaderRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/payloads.BinningHeaderResponses"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "payloads.BinningDetailResponses": {
            "type": "object",
            "properties": {
                "binDocNo": {
                    "type": "string"
                },
                "binLineNo": {
                    "type": "string"
                },
                "caseNo": {
                    "type": "string"
                },
                "grpoQty": {
                    "type": "integer"
                },
                "itemCode": {
                    "type": "string"
                },
                "locCode": {
                    "type": "string"
                },
                "poLineNo": {
                    "type": "string"
                }
            }
        },
        "payloads.BinningHeaderRequest": {
            "type": "object",
            "properties": {
                "COMPANY_CODE": {
                    "type": "string"
                },
                "PO_DOC_NO": {
                    "type": "string"
                }
            }
        },
        "payloads.BinningHeaderResponses": {
            "type": "object",
            "properties": {
                "companyCode": {
                    "type": "string"
                },
                "item": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payloads.BinningDetailResponses"
                    }
                },
                "poDocNo": {
                    "type": "string"
                },
                "whscode": {
                    "type": "string"
                },
                "whsgroup": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/http://localhost:3030/",
	Schemes:          []string{},
	Title:            "Binning List",
	Description:      "This is a practice api spec for getting binning list.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
